"""Stage 02: extract a born-digital invoice from its PDF text layer.

The fast path. When a warehouse sends a PDF generated by their billing system
rather than a scan, the characters are already in the file: reading them is
exact, free, offline and deterministic, and no model can misread a rate that
was never rendered to pixels.

The whole design rule here is **defer rather than guess**. A text-layer parser
that half-understands a table produces plausible wrong numbers, which is worse
than producing nothing -- the audit downstream cannot tell a parse error from a
warehouse error. So every uncertainty raises :class:`NotConfident`, and intake
falls through to the vision extractor, which handles layout variation properly.

Requires ``pdfplumber``. Without it the module imports fine and simply never
claims a document.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Iterable

from .intake import IntakeError
from .models import Invoice, InvoiceLine
from .money import money, quantity

#: Below this many characters a page is a picture, not a document.
MIN_TEXT_CHARS = 120

#: Column header synonyms. A table we cannot label confidently is a table we
#: refuse, so this map is the parser's entire notion of what a column means.
_COLUMNS: dict[str, tuple[str, ...]] = {
    "line_no": ("line", "line no", "line #", "no", "#", "item", "item no"),
    "description": ("description", "service", "activity", "charge", "details", "item description"),
    "quantity": ("qty", "quantity", "units", "count", "volume"),
    "uom": ("uom", "unit", "unit of measure", "basis", "per"),
    "unit_rate": ("rate", "unit rate", "price", "unit price", "tariff", "each"),
    "amount": ("amount", "total", "extended", "line total", "value", "charge amount", "ext"),
    "base_amount": ("base", "base amount", "carrier cost", "cost", "pass-through"),
}

_REQUIRED_COLUMNS = ("description", "amount")

_MONEY = re.compile(r"^\(?-?[$£€]?\s*[\d,]+(?:\.\d{1,2})?\)?$")
_CLEAN = re.compile(r"[$£€,\s]")

_META_PATTERNS: dict[str, tuple[re.Pattern[str], ...]] = {
    "invoice_no": (
        re.compile(r"invoice\s*(?:no\.?|number|#)\s*[:#]?\s*([A-Z0-9][A-Z0-9\-/]{2,})", re.I),
        re.compile(r"\binv\s*[:#]\s*([A-Z0-9][A-Z0-9\-/]{2,})", re.I),
    ),
    "invoice_date": (
        re.compile(r"invoice\s*date\s*[:#]?\s*([0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{1,2}[/-][0-9]{1,2}[/-][0-9]{2,4}|[0-9]{1,2}\s+\w+\s+[0-9]{4})", re.I),
        re.compile(r"\bdated?\s*[:#]?\s*([0-9]{4}-[0-9]{2}-[0-9]{2})", re.I),
    ),
    "stated_total": (
        re.compile(r"(?:invoice\s*)?total\s*(?:due)?\s*[:#]?\s*[$£€]?\s*([\d,]+\.\d{2})", re.I),
        re.compile(r"amount\s*due\s*[:#]?\s*[$£€]?\s*([\d,]+\.\d{2})", re.I),
    ),
    "warehouse_id": (re.compile(r"warehouse\s*(?:id|code)?\s*[:#]\s*([A-Z0-9][A-Z0-9\-]{1,})", re.I),),
    "client_id": (re.compile(r"(?:client|account|customer)\s*(?:id|code)?\s*[:#]\s*([A-Z0-9][A-Z0-9\-]{1,})", re.I),),
    "currency": (re.compile(r"\b(USD|GBP|EUR|CAD)\b"),),
}

_PERIOD = re.compile(
    r"(?:service\s*)?period\s*[:#]?\s*"
    r"([0-9]{4}-[0-9]{2}-[0-9]{2})\s*(?:to|-|–|\.\.)\s*([0-9]{4}-[0-9]{2}-[0-9]{2})",
    re.I,
)
_PERIOD_MONTH = re.compile(
    r"(?:service\s*)?period\s*[:#]?\s*(\w+)\s+([0-9]{4})", re.I
)


class NotConfident(Exception):
    """This parser will not claim the document. Intake falls through to vision."""


def available() -> bool:
    try:
        import pdfplumber  # noqa: F401
    except ImportError:
        return False
    return True


def _norm(text: object) -> str:
    return re.sub(r"\s+", " ", str(text or "")).strip().lower()


def _looks_like_money(cell: str) -> bool:
    return bool(_MONEY.match(cell.strip()))


def _to_decimal(cell: str) -> Decimal:
    text = _CLEAN.sub("", cell.strip())
    negative = text.startswith("(") and text.endswith(")")
    text = text.strip("()")
    try:
        value = money(text)
    except (InvalidOperation, ValueError, TypeError) as exc:
        raise NotConfident(f"not a number: {cell!r}") from exc
    return -value if negative else value


def _parse_date(text: str) -> date:
    text = text.strip()
    for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y", "%d-%m-%Y", "%d %B %Y", "%d %b %Y"):
        try:
            return datetime.strptime(text, fmt).date()
        except ValueError:
            continue
    raise NotConfident(f"unreadable date: {text!r}")


def _month_range(name: str, year: str) -> tuple[date, date]:
    import calendar

    for fmt in ("%B", "%b"):
        try:
            month = datetime.strptime(name, fmt).month
            break
        except ValueError:
            continue
    else:
        raise NotConfident(f"unreadable month: {name!r}")
    y = int(year)
    return date(y, month, 1), date(y, month, calendar.monthrange(y, month)[1])


def _map_header(row: Iterable[Any]) -> dict[int, str] | None:
    """Label each column, or return None if this row is not a header."""
    mapping: dict[int, str] = {}
    for index, cell in enumerate(row):
        text = _norm(cell)
        if not text:
            continue
        for field, synonyms in _COLUMNS.items():
            if text in synonyms and field not in mapping.values():
                mapping[index] = field
                break
    if not all(f in mapping.values() for f in _REQUIRED_COLUMNS):
        return None
    return mapping


@dataclass
class PdfTextExtractor:
    """Reads the PDF text layer. Refuses anything it cannot read exactly."""

    warehouse_id: str | None = None
    client_id: str | None = None
    min_text_chars: int = MIN_TEXT_CHARS

    def supports(self, path: Path) -> bool:
        return Path(path).suffix.lower() == ".pdf" and available()

    # -- probing -----------------------------------------------------------

    def has_text_layer(self, path: Path) -> bool:
        """True when the pages carry real characters rather than an image."""
        import pdfplumber

        try:
            with pdfplumber.open(str(path)) as pdf:
                chars = sum(len((page.extract_text() or "").strip()) for page in pdf.pages)
        except Exception:
            return False
        return chars >= self.min_text_chars

    # -- extraction --------------------------------------------------------

    def extract(self, path: Path) -> Invoice:
        """Raises :class:`NotConfident` whenever vision should take over."""
        import pdfplumber

        path = Path(path)
        try:
            with pdfplumber.open(str(path)) as pdf:
                pages = [(n, page.extract_text() or "", page.extract_tables() or [])
                         for n, page in enumerate(pdf.pages, start=1)]
        except Exception as exc:
            raise NotConfident(f"{path.name}: pdfplumber could not open it ({exc})") from exc

        text = "\n".join(body for _, body, _ in pages)
        if len(text.strip()) < self.min_text_chars:
            raise NotConfident(f"{path.name}: no usable text layer (a scan)")

        meta = self._metadata(text)
        lines = self._lines(pages)
        if not lines:
            raise NotConfident(f"{path.name}: no line-item table recognised")

        warehouse_id = self.warehouse_id or meta.get("warehouse_id")
        client_id = self.client_id or meta.get("client_id")
        if not warehouse_id or not client_id:
            raise NotConfident(f"{path.name}: warehouse or client not stated")

        for field in ("invoice_no", "invoice_date", "period_start", "stated_total"):
            if field not in meta:
                raise NotConfident(f"{path.name}: could not read {field}")

        invoice = Invoice(
            invoice_no=meta["invoice_no"],
            warehouse_id=str(warehouse_id),
            client_id=str(client_id),
            invoice_date=meta["invoice_date"],
            period_start=meta["period_start"],
            period_end=meta["period_end"],
            lines=lines,
            stated_total=meta["stated_total"],
            currency=meta.get("currency", "USD"),
            source_path=str(path),
        )

        # The parser's own self-check. The lines must add up to the printed
        # total; if they do not, we have most likely dropped or double-read a
        # row, and a dropped row would surface later as a MISSING_LINE flag
        # against the warehouse for our own parsing mistake.
        if invoice.line_total != invoice.stated_total:
            raise NotConfident(
                f"{path.name}: parsed lines total {invoice.line_total} but the "
                f"invoice states {invoice.stated_total} — cannot tell a parse "
                "error from a billing error, so deferring"
            )

        return invoice

    # -- internals ---------------------------------------------------------

    def _metadata(self, text: str) -> dict[str, Any]:
        found: dict[str, Any] = {}
        for field, patterns in _META_PATTERNS.items():
            for pattern in patterns:
                match = pattern.search(text)
                if not match:
                    continue
                raw = match.group(1).strip()
                if field == "invoice_date":
                    found[field] = _parse_date(raw)
                elif field == "stated_total":
                    found[field] = _to_decimal(raw)
                else:
                    found[field] = raw
                break

        period = _PERIOD.search(text)
        if period:
            found["period_start"] = _parse_date(period.group(1))
            found["period_end"] = _parse_date(period.group(2))
        else:
            month = _PERIOD_MONTH.search(text)
            if month:
                start, end = _month_range(month.group(1), month.group(2))
                found["period_start"], found["period_end"] = start, end
        return found

    def _lines(self, pages: list[tuple[int, str, list]]) -> list[InvoiceLine]:
        lines: list[InvoiceLine] = []
        seen_header = False

        for page_no, _, tables in pages:
            for table in tables:
                mapping: dict[int, str] | None = None
                for row in table:
                    if mapping is None:
                        mapping = _map_header(row)
                        if mapping is not None:
                            seen_header = True
                        continue
                    parsed = self._row(row, mapping, page_no, len(lines) + 1)
                    if parsed is not None:
                        lines.append(parsed)

        if not seen_header:
            raise NotConfident("no table header could be labelled")
        return lines

    def _row(
        self,
        row: list[Any],
        mapping: dict[int, str],
        page_no: int,
        fallback_no: int,
    ) -> InvoiceLine | None:
        cells = {mapping[i]: str(row[i] or "").strip()
                 for i in mapping
                 if i < len(row)}

        description = re.sub(r"\s+", " ", cells.get("description", "")).strip()
        amount_cell = cells.get("amount", "")
        if not description or not amount_cell:
            return None
        # Totals and subtotals repeat the amount column without being lines.
        if re.match(r"^(sub)?total\b", description, re.I):
            return None
        if not _looks_like_money(amount_cell):
            raise NotConfident(
                f'line "{description}" has an unreadable amount: {amount_cell!r}'
            )

        line_no_cell = cells.get("line_no", "")
        try:
            line_no = int(re.sub(r"\D", "", line_no_cell)) if line_no_cell else fallback_no
        except ValueError:
            line_no = fallback_no

        qty_cell = cells.get("quantity", "")
        rate_cell = cells.get("unit_rate", "")
        base_cell = cells.get("base_amount", "")

        return InvoiceLine(
            line_no=line_no,
            description=description,
            quantity=quantity(_CLEAN.sub("", qty_cell)) if qty_cell else Decimal(0),
            amount=_to_decimal(amount_cell),
            uom=cells.get("uom") or None,
            unit_rate=_to_decimal(rate_cell) if rate_cell and _looks_like_money(rate_cell) else None,
            base_amount=_to_decimal(base_cell) if base_cell and _looks_like_money(base_cell) else None,
            source_page=page_no,
            # Deliberately None: a text-layer read is exact, so it must never
            # trip LOW_CONFIDENCE_EXTRACTION the way a transcription can.
            extract_confidence=None,
        )
